server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/kafka_inventory
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      group-id: inventory-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        max.poll.records: 10
        max.poll.interval.ms: 300000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
        spring.json.trusted.packages: "*"

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: cut

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: ete

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: drt

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN